### ISSUE TITLE
og:image meta tag does not show correct image in link preview

### ISSUE THREAD

**Issue by flutter-clutter** [signalapp/Signal-iOS#5559]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The link preview when sending a message does not display the open graph image which I provide in my website's `og:image` meta tag. An example URL that causes this issue is this: https://www.flutterclutter.dev/flutter/tutorials/flutter-game-tutorial-fruit-ninja-clone/2020/951/

### Steps to reproduce
Put a signal message with https://www.flutterclutter.dev/flutter/tutorials/flutter-game-tutorial-fruit-ninja-clone/2020/951/ into the message field (you might also want to send it but the link preview is already generated beforehand).
It seems to generate a fallback image based on the favicon although a proper image is described in the `og:image` tag.
Websites like this [og check](https://www.opengraph.xyz/) display everything seamlessly.

**Actual result:** It seems to generate a fallback image based on the favicon instead of the image provided in the `og` tags.

**Expected result:** Render the same images that are shown in [common og checks](https://www.opengraph.xyz/).

### Screenshots

<img src="https://user-images.githubusercontent.com/67044108/224244018-af35acc8-f74c-4a16-b3a9-06615d396b59.jpeg" width="300">

### Device info
**Device**: iPhone 12 Mini

**iOS version**: iOS 16.2

**Signal version:** 6.12

Also happens on Mac version (6.9.0 Apple Silicon).

This is related to [this issue](https://github.com/signalapp/Signal-iOS/issues/5465) that was closed automatically.

**Comment by Onyoursix** [comment]
I'm also having this same issue. Image loads on every platform, passes all the checks, just doesn't load on signal.

**Comment by sashaweiss-signal** [comment]
Hi! It looks like on the page you linked, the `<meta>` tag is as such:

```html
<meta name="og:image" content="https://www.flutterclutter.dev/images/posts/2020-07-24-flutter-game-tutorial-fruit-ninja-clone/flutter-fruit-ninja-clone.png">
```

From what I can tell on https://ogp.me, the `name=` should in fact be `property=`. Looking at Signal's code, we parse `og:image` meta tags looking for `property=`. Additionally, the other `meta` tags with `og:` data on that page use `property=`, so I suspect the `og:image` tag using `name=` is an oversight.

I'm going to close this, as I don't think the fix lives on the Signal side. Thanks for reporting!

**Comment by jonsherrard** [comment]
I'm also running into this bug, doing some testing now but have noticed that both reports here are .png files, as are images generated by the @vercel/og repo, and the ones that I have _working_ are jpg files.

Works: https://www.theguardian.com/sport/2023/oct/16/england-little-option-ben-stokes-cricket-world-cup (jpg)

```html
<meta property="og:image:width" content="1200"/>
<meta property="og:image" content="https://i.guim.co.uk/img/media/4784134da1b0485a25c2867207e43000fbf301b0/0_23_5012_3006/master/5012.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=c6c6ebbef2067ab804e5a09709825dbe"/>
<meta property="og:image:height" content="720"/>
 ```
 
Doesn't work: https://ashore.io/journal/desk-notes/unbundling-the-office (png)

```html
<meta property="og:image" content="https://ashore.io/api/og-images/basic-article?slug=unbundling-the-office&amp;v=zBYb2h22dPHXIc8JX9mkpE"/>
<meta property="og:image:alt" content="Unbundling The Office"/>
<meta property="og:image:secure_url" content="https://ashore.io/api/og-images/basic-article?slug=unbundling-the-office&amp;v=zBYb2h22dPHXIc8JX9mkpE"/>
<meta property="og:image:type" content="image/png"/>
<meta property="og:image:width" content="1200"/>
<meta property="og:image:height" content="630"/>
```

**Comment by nalinbhardwaj** [comment]
@jonsherrard did you find a fix to this?

**Comment by jonsherrard** [comment]
> @jonsherrard did you find a fix to this? I'm using `@vercel/og` for generation and previews don't load for me either

I proxy the OG images through a next.js API call 😂

```ts

export const config = {
  api: {
    bodyParser: false,
    externalResolver: true,
  },
};

// api endpoint here:
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<Buffer>
) {
  const { title, subtitle } = req.query;
  if (req.headers["transfer-encoding"] === "chunked") {
    (req as any).filePayload = JSON.parse((await getRawBody(req)).toString());
  }

  const url = `${baseUrl()}/api/v1/public/og-images/basic-image.png?title=${title}&subtitle=${subtitle}`;

  const response = await fetch(url as string);
  const buffer = await response.buffer();

  // mesure the length of the buffer in bytes
  const bufferLength = Buffer.byteLength(buffer);

  // disable content encoding on this response
  res.setHeader("Content-Type", "image/png");
  res.setHeader("Internal-Image-Proxy", "true");
  res.setHeader("Content-Length", bufferLength);
  // return the image buffer as png here
  res.status(200).send(buffer);
}

```

**Comment by Pfed-prog** [comment]
My understanding is that in general we should use property instead of name in all meta tags

**Comment by ryan-williams** [comment]
Similar @jonsherrard [above](https://github.com/signalapp/Signal-iOS/issues/5559#issuecomment-1765099353), Signal fails to load my PNG `og:image` (on macOS and Android), but works with a JPG:

```html
<!-- ❌ PNG doesn't work -->
<meta property="og:image" content="https://bw25.hccs.dev/hccs-data-cover.png" />
<!-- ✅ JPG works -->
<meta property="og:image" content="https://bw25.hccs.dev/hccs-data-cover.jpg" />
```

Here are the images:
- ❌ https://bw25.hccs.dev/hccs-data-cover.png
- ✅ https://bw25.hccs.dev/hccs-data-cover.jpg

Some more metadata about each:
```bash
file hccs-data-cover.jpg
# hccs-data-cover.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=1], baseline, precision 8, 1715x951, components 3
file hccs-data-cover.png
# hccs-data-cover.png: PNG image data, 2674 x 1516, 8-bit/color RGBA, non-interlaced
ls -lh hccs-data-cover.*
# -rw-r--r-- 1 ryan staff 634K Apr  1 11:46 hccs-data-cover.jpg
# -rw-r--r-- 1 ryan staff 3.1M Apr  1 11:46 hccs-data-cover.png
```

Perhaps Signal doesn't like the 3.1M PNG? [opengraph.xyz](https://www.opengraph.xyz/url/https%3A%2F%2Fbw25.hccs.dev) was happy with it (even before I switched to JPG), Facebook/X/LinkedIn/Discord previews all looked good; Signal seems clearly behind other services here.

**Comment by midzer** [comment]
~~Just figured out that a `~` in an URL leads to image preview not generated at all.~~

Edit: Sorry, figured out we did not allow

```
"text/*" in request.headers["accept"] or
"*/*" in request.headers["accept"]:
```

in FastAPI backend for a specific page.
